language: ruby
branches:
  only:
    - "master"
    - "/^release-/"
rvm:
  - 2.2.0
before_install:
  - apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
  - echo "deb http://dist.crystal-lang.org/apt crystal main" > /etc/apt/sources.list.d/crystal.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq libaspell-dev aspell-en
  - sudo apt-get install -qq crystal
cache: bundler
sudo: required
git:
  depth: 10
